name: SavageCore
version: 1.3-STABLE
main: me.ryder.savagecore.SavageCore
api-version: '1.13'
authors: [Ryder]
description: A plugin to improve the Factions experience.
commands:
  sc:
    aliases:
      - savagecore
    description: The base commands for SavageCore
permissions:
  savagecore.reload:
    description: Allows you to reload the plugin.
  savagecore.view:
    description: Displays a list of commands.
